apiVersion: v1
kind: Pod
metadata:
  labels:
    run: prod-failover-pod
  name: prod-failover-pod
  namespace: demo
spec:
  containers:
  - args:
    - sleep
    - "600"
    image: busybox
    name: prod-failover-pod
