---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: app
  namespace: demo
spec:
  releaseName: app
  chart:
    git: ssh://git@test.com/sly01/flux-get-started
    ref: master
    path: charts/app
  values:
    image:
      repository: docker.io/bitnami/nginx
      tag: 1.21.6
