apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webserver1
  name: webserver1
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver1
  template:
    metadata:
      labels:
        app: webserver1
    spec:
      containers:
      - image: nginx
        name: nginx
