apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webserver2
  name: webserver2
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver2
  template:
    metadata:
      labels:
        app: webserver2
    spec:
      containers:
      - image: nginx
        name: nginx
