---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: app
  namespace: demo
spec:
  releaseName: app
  chart:
    git: ssh://git@github.com/sly01/flux-get-started
    ref: master
    path: charts/app
  values:
    image:
      tag: 1.21.1
