---
apiVersion: v1
data:
  index.html: |
    <h1>Hello from app2</h1>
kind: ConfigMap
metadata:
  name: nginx-index-app2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app2
  name: app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: nginx-html
      volumes:
      - name: nginx-html
        configMap:
          name: nginx-index-app2
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app2-service
  name: app2-service
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: app2
  type: ClusterIP
